using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using CustomFinancialPlanningAssistant.Core.DTOs;
using CustomFinancialPlanningAssistant.Core.Entities;
using CustomFinancialPlanningAssistant.Infrastructure.Repositories;
using CustomFinancialPlanningAssistant.Services.Financial;
using Microsoft.Extensions.Logging;

namespace CustomFinancialPlanningAssistant.Services.Reports;

/// <summary>
/// Service for generating professional PDF reports using QuestPDF
/// </summary>
public class PdfReportService
{
    private readonly IFinancialService _financialService;
    private readonly IFinancialDocumentRepository _documentRepo;
    private readonly ILogger<PdfReportService> _logger;
    
    public PdfReportService(
        IFinancialService financialService,
        IFinancialDocumentRepository documentRepo,
        ILogger<PdfReportService> logger)
    {
        _financialService = financialService;
        _documentRepo = documentRepo;
        _logger = logger;
    }
    
    /// <summary>
    /// Generates a PDF report based on options
    /// </summary>
    public async Task<byte[]> GeneratePdfReportAsync(int documentId, ReportGenerationOptions options)
    {
        try
        {
            _logger.LogInformation($"Generating PDF report for document {documentId}");
            
            // Get data
            var summary = await _financialService.GetFinancialSummaryAsync(documentId);
            var document = await _documentRepo.GetWithDataAsync(documentId);
            
            // Generate PDF based on report type
            var pdfBytes = options.ReportType switch
            {
                Core.Enums.ReportType.Summary => GenerateExecutiveSummary(summary, options),
                Core.Enums.ReportType.Detailed => await GenerateComprehensiveReport(documentId, summary, document, options),
                Core.Enums.ReportType.RatioAnalysis => await GenerateRatioAnalysisReport(documentId, summary, options),
                _ => GenerateExecutiveSummary(summary, options)
            };
            
            _logger.LogInformation("PDF report generated successfully");
            return pdfBytes;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating PDF report");
            throw;
        }
    }
    
    /// <summary>
    /// Executive Summary - 1 page overview
    /// </summary>
    private byte[] GenerateExecutiveSummary(FinancialSummaryDto summary, ReportGenerationOptions options)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x.FontSize(11).FontColor(Colors.Grey.Darken3));
                
                page.Header().Element(c => CreateHeader(c, options));
                page.Content().Element(c => CreateExecutiveSummaryContent(c, summary));
                page.Footer().AlignCenter().Text($"Generated by Financial Analysis Assistant | {DateTime.Now:yyyy-MM-dd HH:mm}")
                    .FontSize(9).FontColor(Colors.Grey.Medium);
            });
        });
        
        return document.GeneratePdf();
    }
    
    /// <summary>
    /// Comprehensive Report - Multi-page with all details
    /// </summary>
    private async Task<byte[]> GenerateComprehensiveReport(
        int documentId, 
        FinancialSummaryDto summary, 
        FinancialDocument document, 
        ReportGenerationOptions options)
    {
        var ratios = await _financialService.CalculateFinancialRatiosAsync(documentId);
        
        var pdfDocument = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x.FontSize(11).FontColor(Colors.Grey.Darken3));
                
                page.Header().Element(c => CreateHeader(c, options));
                
                page.Content().Column(column =>
                {
                    // Page 1: Executive Summary
                    column.Item().Element(c => CreateExecutiveSummaryContent(c, summary));
                    
                    // Page Break
                    column.Item().PageBreak();
                    
                    // Page 2: Financial Ratios
                    column.Item().Element(c => CreateRatiosContent(c, ratios));
                    
                    // Page Break
                    column.Item().PageBreak();
                    
                    // Page 3+: Detailed Data
                    column.Item().Element(c => CreateDetailedDataContent(c, document.FinancialDataRecords.ToList()));
                });
                
                page.Footer().AlignCenter().Text($"Generated by Financial Analysis Assistant | {DateTime.Now:yyyy-MM-dd HH:mm}")
                    .FontSize(9).FontColor(Colors.Grey.Medium);
            });
        });
        
        return pdfDocument.GeneratePdf();
    }
    
    /// <summary>
    /// Ratio Analysis Report - Focus on financial ratios
    /// </summary>
    private async Task<byte[]> GenerateRatioAnalysisReport(
        int documentId, 
        FinancialSummaryDto summary, 
        ReportGenerationOptions options)
    {
        var ratios = await _financialService.CalculateFinancialRatiosAsync(documentId);
        
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x.FontSize(11).FontColor(Colors.Grey.Darken3));
                
                page.Header().Element(c => CreateHeader(c, options));
                
                page.Content().Column(column =>
                {
                    // Summary section
                    column.Item().PaddingBottom(10).Text("Financial Overview")
                        .FontSize(16).Bold().FontColor(Colors.Blue.Darken2);
                    
                    column.Item().Element(c => CreateSummaryTable(c, summary));
                    
                    column.Item().PaddingVertical(15).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                    
                    // Ratios section
                    column.Item().Element(c => CreateRatiosContent(c, ratios));
                });
                
                page.Footer().AlignCenter().Text($"Generated by Financial Analysis Assistant | {DateTime.Now:yyyy-MM-dd HH:mm}")
                    .FontSize(9).FontColor(Colors.Grey.Medium);
            });
        });
        
        return document.GeneratePdf();
    }
    
    // ===== HEADER =====
    
    private void CreateHeader(IContainer container, ReportGenerationOptions options)
    {
        container.Column(column =>
        {
            // Title
            column.Item().AlignCenter().Text(options.Title ?? "Financial Analysis Report")
                .FontSize(20).Bold().FontColor(Colors.Blue.Darken2);
            
            // Company name if provided
            if (!string.IsNullOrWhiteSpace(options.CompanyName))
            {
                column.Item().AlignCenter().Text(options.CompanyName)
                    .FontSize(14).SemiBold().FontColor(Colors.Grey.Darken1);
            }
            
            // Report date
            column.Item().AlignCenter().PaddingTop(5).Text($"Report Date: {(options.ReportDate ?? DateTime.Now):MMMM dd, yyyy}")
                .FontSize(10).FontColor(Colors.Grey.Medium);
            
            // Separator line
            column.Item().PaddingTop(10).PaddingBottom(10)
                .LineHorizontal(1).LineColor(Colors.Grey.Lighten1);
        });
    }
    
    // ===== CONTENT SECTIONS =====
    
    private void CreateExecutiveSummaryContent(IContainer container, FinancialSummaryDto summary)
    {
        container.Column(column =>
        {
            // Key Metrics Cards
            column.Item().PaddingBottom(15).Row(row =>
            {
                row.RelativeItem().Element(c => CreateMetricCard(c, "Total Revenue", summary.TotalRevenue, Colors.Green.Lighten2));
                row.Spacing(10);
                row.RelativeItem().Element(c => CreateMetricCard(c, "Total Expenses", summary.TotalExpenses, Colors.Red.Lighten2));
                row.Spacing(10);
                row.RelativeItem().Element(c => CreateMetricCard(c, "Net Income", summary.NetIncome, 
                    summary.NetIncome > 0 ? Colors.Green.Lighten2 : Colors.Red.Lighten2));
                row.Spacing(10);
                row.RelativeItem().Element(c => CreateMetricCard(c, "Profit Margin", 
                    summary.TotalRevenue > 0 ? (summary.NetIncome / summary.TotalRevenue * 100) : 0, 
                    Colors.Blue.Lighten2, "%"));
            });
            
            // Summary Table
            column.Item().PaddingBottom(10).Text("Financial Summary")
                .FontSize(16).Bold().FontColor(Colors.Blue.Darken2);
            
            column.Item().Element(c => CreateSummaryTable(c, summary));
            
            // Key Highlights
            if (summary.KeyHighlights.Any())
            {
                column.Item().PaddingTop(15).Text("Key Highlights")
                    .FontSize(14).Bold().FontColor(Colors.Blue.Darken2);
                
                column.Item().PaddingTop(5).Column(highlightColumn =>
                {
                    foreach (var highlight in summary.KeyHighlights.Take(5))
                    {
                        highlightColumn.Item().PaddingBottom(5).Row(row =>
                        {
                            row.ConstantItem(20).Text("•").FontColor(Colors.Blue.Darken1);
                            row.RelativeItem().Text(highlight).FontSize(10);
                        });
                    }
                });
            }
        });
    }
    
    private void CreateMetricCard(IContainer container, string label, decimal value, string color, string suffix = "")
    {
        container.Border(1).BorderColor(Colors.Grey.Lighten2).Background(color).Padding(10).Column(column =>
        {
            column.Item().Text(label).FontSize(10).FontColor(Colors.Grey.Darken2);
            column.Item().PaddingTop(5).Text(suffix == "%" ? $"{value:F2}{suffix}" : $"{value:C0}")
                .FontSize(16).Bold().FontColor(Colors.Grey.Darken3);
        });
    }
    
    private void CreateSummaryTable(IContainer container, FinancialSummaryDto summary)
    {
        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn(2);
                columns.RelativeColumn(1);
            });
            
            // Header
            table.Header(header =>
            {
                header.Cell().Background(Colors.Blue.Darken2).Padding(8)
                    .Text("Metric").FontColor(Colors.White).Bold();
                header.Cell().Background(Colors.Blue.Darken2).Padding(8)
                    .Text("Amount").FontColor(Colors.White).Bold().AlignRight();
            });
            
            // Rows - using inline cells instead of helper method
            table.Cell().Background(Colors.Green.Lighten4).Padding(6).Text("Total Revenue");
            table.Cell().Background(Colors.Green.Lighten4).Padding(6).Text($"{summary.TotalRevenue:C}").AlignRight();
            
            table.Cell().Background(Colors.Red.Lighten4).Padding(6).Text("Total Expenses");
            table.Cell().Background(Colors.Red.Lighten4).Padding(6).Text($"{summary.TotalExpenses:C}").AlignRight();
            
            var incomeColor = summary.NetIncome > 0 ? Colors.Green.Lighten4 : Colors.Red.Lighten4;
            table.Cell().Background(incomeColor).Padding(6).Text("Net Income").Bold();
            table.Cell().Background(incomeColor).Padding(6).Text($"{summary.NetIncome:C}").Bold().AlignRight();
            
            table.Cell().Background(Colors.White).Padding(6).Text("Total Assets");
            table.Cell().Background(Colors.White).Padding(6).Text($"{summary.TotalAssets:C}").AlignRight();
            
            table.Cell().Background(Colors.White).Padding(6).Text("Total Liabilities");
            table.Cell().Background(Colors.White).Padding(6).Text($"{summary.TotalLiabilities:C}").AlignRight();
            
            table.Cell().Background(Colors.Grey.Lighten4).Padding(6).Text("Equity").Bold();
            table.Cell().Background(Colors.Grey.Lighten4).Padding(6).Text($"{summary.Equity:C}").Bold().AlignRight();
        });
    }
    
    private void CreateRatiosContent(IContainer container, Dictionary<string, decimal> ratios)
    {
        container.Column(column =>
        {
            column.Item().PaddingBottom(10).Text("Financial Ratios Analysis")
                .FontSize(16).Bold().FontColor(Colors.Blue.Darken2);
            
            column.Item().Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(2);
                    columns.RelativeColumn(1);
                });
                
                // Header
                table.Header(header =>
                {
                    header.Cell().Background(Colors.Blue.Darken2).Padding(8)
                        .Text("Ratio Name").FontColor(Colors.White).Bold();
                    header.Cell().Background(Colors.Blue.Darken2).Padding(8)
                        .Text("Value").FontColor(Colors.White).Bold().AlignRight();
                });
                
                // Rows
                bool alternate = false;
                foreach (var ratio in ratios)
                {
                    var bgColor = alternate ? Colors.Grey.Lighten4 : Colors.White;
                    table.Cell().Background(bgColor).Padding(6).Text(FormatRatioName(ratio.Key));
                    table.Cell().Background(bgColor).Padding(6).Text($"{ratio.Value:F2}").AlignRight();
                    alternate = !alternate;
                }
            });
        });
    }
    
    private void CreateDetailedDataContent(IContainer container, List<FinancialData> data)
    {
        container.Column(column =>
        {
            column.Item().PaddingBottom(10).Text("Detailed Financial Data")
                .FontSize(16).Bold().FontColor(Colors.Blue.Darken2);
            
            column.Item().Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(3);
                    columns.RelativeColumn(2);
                    columns.RelativeColumn(1.5f);
                    columns.RelativeColumn(1.5f);
                });
                
                // Header
                table.Header(header =>
                {
                    header.Cell().Background(Colors.Blue.Darken2).Padding(5)
                        .Text("Account Name").FontColor(Colors.White).Bold().FontSize(9);
                    header.Cell().Background(Colors.Blue.Darken2).Padding(5)
                        .Text("Category").FontColor(Colors.White).Bold().FontSize(9);
                    header.Cell().Background(Colors.Blue.Darken2).Padding(5)
                        .Text("Period").FontColor(Colors.White).Bold().FontSize(9);
                    header.Cell().Background(Colors.Blue.Darken2).Padding(5)
                        .Text("Amount").FontColor(Colors.White).Bold().AlignRight().FontSize(9);
                });
                
                // Rows (limit to prevent huge PDFs)
                bool alternate = false;
                foreach (var item in data.OrderBy(d => d.Category).ThenBy(d => d.AccountName).Take(100))
                {
                    var bgColor = alternate ? Colors.Grey.Lighten4 : Colors.White;
                    table.Cell().Background(bgColor).Padding(4).Text(item.AccountName).FontSize(8);
                    table.Cell().Background(bgColor).Padding(4).Text(item.Category).FontSize(8);
                    table.Cell().Background(bgColor).Padding(4).Text(item.Period).FontSize(8);
                    table.Cell().Background(bgColor).Padding(4).Text($"{item.Amount:C}").AlignRight().FontSize(8);
                    alternate = !alternate;
                }
                
                if (data.Count > 100)
                {
                    table.Cell().ColumnSpan(4).Padding(8).AlignCenter()
                        .Text($"Showing first 100 of {data.Count} records. Export to Excel for complete data.")
                        .FontSize(9).Italic().FontColor(Colors.Grey.Medium);
                }
            });
        });
    }
    
    // ===== HELPER METHODS =====
    
    private string FormatRatioName(string ratioKey)
    {
        return System.Text.RegularExpressions.Regex.Replace(ratioKey, "([A-Z])", " $1").Trim();
    }
}
